import { Geist, Geist_Mono } from "next/font/google";
import { AuthProvider } from "@/components/context/AuthContext";
import HeaderWrapper from "@/components/headers/HeaderWrapper"; // ⬅️ Crée ce composant client
import Footer from "@/components/footers/Footer";
import "./globals.css";

const geistSans = Geist({
 variable: "--font-geist-sans",
 subsets: ["latin"],
});

const geistMono = Geist_Mono({
 variable: "--font-geist-mono",
 subsets: ["latin"],
});

export const metadata = {
 title: "Create Next App",
 description: "Generated by create next app",
};

export default function RootLayout({ children }) {
 return (
  <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
   <body className="flex flex-col min-h-screen h-full overflow-hidden">
    <AuthProvider>
     <HeaderWrapper /> {/* <-- Déplace la logique client ici */}
     <main className="flex-grow flex flex-col">{children}</main>
     <Footer />
    </AuthProvider>
   </body>
  </html>
 );
}
